#!/usr/bin/env python3
"""
文言文省 Token 引擎 (Classical Chinese Token Saver)

原理：现代汉语平均 1 token/字，文言文平均 0.5 token/字（因其凝练性）。
在不影响语义、可读性、执行准确性的前提下，将中文提示/代码注释
转换为文言文，降低 Token 消耗。

使用前提（严格检查）：
1. 必须是中文语境
2. 任务不涉及与人类的自然语言交互（最终输出仍须现代汉语）
3. 转换后语义必须 100% 等价
4. 代码逻辑、变量名、API 调用不可变更
5. 仅转换内部思考/注释/中间提示，不转换最终交付物

策略：
- 内部 chain-of-thought → 文言简牍
- 代码注释 → 文言批注
- 系统提示中的冗长说明 → 文言诏令体
- 记忆摘要 → 文言编年
"""

from __future__ import annotations

import re
from typing import Callable

# ── 转换规则库 ──

CLASSICAL_PATTERNS: list[tuple[str, str]] = [
    # 常见冗余 → 文言凝练
    (r"首先，我们需要", "先须"),
    (r"接下来，", "次"),
    (r"然后，", "继而"),
    (r"最后，", "终"),
    (r"总之，", "总之"),
    (r"也就是说，", "即"),
    (r"这意味着", "意谓"),
    (r"因此，", "故"),
    (r"所以，", "是以"),
    (r"因为", "因"),
    (r"但是", "然"),
    (r"然而", "然"),
    (r"不过", "惟"),
    (r"虽然", "虽"),
    (r"如果", "若"),
    (r"假设", "设若"),
    (r"例如", "譬如"),
    (r"比如", "譬"),
    (r"等等", "云云"),
    (r"等等等", "诸如此类"),
    (r"非常重要", "至关重"),
    (r"非常重要", "至重"),
    (r"需要注意", "宜注意"),
    (r"需要特别", "尤须"),
    (r"我们必须", "吾侪当"),
    (r"我们应该", "宜"),
    (r"我们可以", "可"),
    (r"已经", "已"),
    (r"正在", "方"),
    (r"将要", "将"),
    (r"能够", "能"),
    (r"可能", "或"),
    (r"没有问题", "无虞"),
    (r"出现了问题", "生变"),
    (r"出现错误", "出错了"),
    (r"成功", "成"),
    (r"失败", "败"),
    (r"完成", "毕"),
    (r"开始", "启"),
    (r"结束", "终"),
    (r"暂停", "辍"),
    (r"继续", "续"),
    (r"等待", "俟"),
    (r"检查", "察"),
    (r"验证", "验"),
    (r"确认", "确"),
    (r"创建", "建"),
    (r"删除", "删"),
    (r"修改", "改"),
    (r"读取", "读"),
    (r"写入", "写"),
    (r"更新", "更"),
    (r"获取", "取"),
    (r"设置", "置"),
    (r"返回", "返"),
    (r"调用", "召"),
    (r"执行", "行"),
    (r"运行", "运"),
    (r"停止", "止"),
    (r"启动", "启"),
    (r"初始化", "初置"),
    (r"配置", "配"),
    (r"安装", "装"),
    (r"卸载", "卸"),
    (r"部署", "布"),
    (r"测试", "测"),
    (r"调试", "调"),
    (r"修复", "修"),
    (r"优化", "优"),
    (r"重构", "重构"),
    (r"提交", "交"),
    (r"合并", "合"),
    (r"分支", "枝"),
    (r"冲突", "冲"),
    (r"解决", "解"),
    (r"查找", "寻"),
    (r"搜索", "索"),
    (r"匹配", "匹"),
    (r"过滤", "滤"),
    (r"排序", "序"),
    (r"分组", "组"),
    (r"聚合", "聚"),
    (r"统计", "计"),
    (r"计算", "算"),
    (r"分析", "析"),
    (r"比较", "较"),
    (r"评估", "估"),
    (r"监控", "监"),
    (r"报警", "警"),
    (r"通知", "告"),
    (r"提醒", "提"),
    (r"记录", "录"),
    (r"日志", "志"),
    (r"追踪", "踪"),
    (r"回溯", "溯"),
    (r"恢复", "复"),
    (r"备份", "备"),
    (r"还原", "原"),
    (r"同步", "同"),
    (r"异步", "异步"),
    (r"并发", "并"),
    (r"并行", "并"),
    (r"串行", "串"),
    (r"队列", "列"),
    (r"缓存", "缓"),
    (r"内存", "存"),
    (r"磁盘", "盘"),
    (r"网络", "网"),
    (r"数据库", "库"),
    (r"表", "表"),
    (r"字段", "栏"),
    (r"索引", "引"),
    (r"查询", "询"),
    (r"插入", "插"),
    (r"删除", "删"),
    (r"更新", "更"),
    (r"事务", "务"),
    (r"锁", "锁"),
    (r"死锁", "死锁"),
    (r"超时", "逾时"),
    (r"重试", "重试"),
    (r"降级", "降"),
    (r"熔断", "断"),
    (r"限流", "限"),
    (r"负载", "荷"),
    (r"均衡", "衡"),
    (r"扩容", "扩"),
    (r"缩容", "缩"),
    (r"滚动", "滚"),
    (r"发布", "发"),
    (r"回滚", "回"),
    (r"蓝绿", "蓝绿"),
    (r"灰度", "灰度"),
    (r"金丝雀", "金丝雀"),
    (r"A/B", "A/B"),
    (r"分流", "分流"),
    (r"染色", "染"),
    (r"标记", "标"),
    (r"追踪", "踪"),
    (r"链路", "链"),
    (r"拓扑", "拓扑"),
    (r"依赖", "赖"),
    (r"循环", "环"),
    (r"递归", "递归"),
    (r"迭代", "迭"),
    (r"遍历", "遍"),
    (r"深度", "深"),
    (r"广度", "广"),
    (r"优先", "优"),
    (r"队列", "列"),
    (r"栈", "栈"),
    (r"堆", "堆"),
    (r"树", "树"),
    (r"图", "图"),
    (r"节点", "节"),
    (r"边", "边"),
    (r"权重", "权"),
    (r"路径", "径"),
    (r"最短", "最短"),
    (r"最长", "最长"),
    (r"最小", "最小"),
    (r"最大", "最大"),
    (r"平均", "均"),
    (r"总和", "总"),
    (r"计数", "数"),
    (r"去重", "去重"),
    (r"唯一", "唯一"),
    (r"重复", "复"),
    (r"差异", "差"),
    (r"变化", "变"),
    (r"趋势", "势"),
    (r"预测", "预"),
    (r"异常", "异"),
    (r"告警", "警"),
    (r"事件", "事"),
    (r"指标", "指"),
    (r"维度", "维"),
    (r"标签", "签"),
    (r"属性", "属"),
    (r"特征", "征"),
    (r"样本", "样"),
    (r"训练", "训"),
    (r"模型", "模"),
    (r"推理", "推"),
    (r"部署", "布"),
    (r"服务", "服"),
    (r"接口", "口"),
    (r"协议", "协"),
    (r"格式", "式"),
    (r"编码", "编"),
    (r"解码", "解"),
    (r"压缩", "压"),
    (r"解压", "解"),
    (r"加密", "密"),
    (r"解密", "解"),
    (r"签名", "签"),
    (r"验证", "验"),
    (r"证书", "证"),
    (r"密钥", "钥"),
    (r"令牌", "牌"),
    (r"权限", "权"),
    (r"角色", "角"),
    (r"用户", "户"),
    (r"租户", "租"),
    (r"组织", "组"),
    (r"项目", "项"),
    (r"应用", "应"),
    (r"模块", "块"),
    (r"组件", "件"),
    (r"插件", "插"),
    (r"中间件", "中间"),
    (r"框架", "框"),
    (r"库", "库"),
    (r"包", "包"),
    (r"版本", "版"),
    (r"依赖", "赖"),
    (r"冲突", "冲"),
    (r"兼容", "兼"),
    (r"过期", "逾"),
    (r"废弃", "废"),
    (r"弃用", "弃"),
    (r"标记", "标"),
    (r"注释", "注"),
    (r"文档", "档"),
    (r"说明", "明"),
    (r"示例", "例"),
    (r"演示", "演"),
    (r"教程", "教"),
    (r"指南", "南"),
    (r"手册", "册"),
    (r"规范", "规"),
    (r"标准", "准"),
    (r"最佳实践", "最佳"),
    (r"原则", "则"),
    (r"模式", "式"),
    (r"范式", "范"),
    (r"架构", "构"),
    (r"设计", "计"),
    (r"实现", "现"),
    (r"方案", "案"),
    (r"策略", "策"),
    (r"计划", "划"),
    (r"目标", "的"),
    (r"指标", "指"),
    (r"关键", "要"),
    (r"核心", "核"),
    (r"重点", "重"),
    (r"难点", "难"),
    (r"风险", "险"),
    (r"问题", "题"),
    (r"错误", "误"),
    (r"异常", "异"),
    (r"警告", "警"),
    (r"提示", "示"),
    (r"信息", "信"),
    (r"消息", "息"),
    (r"通知", "告"),
    (r"反馈", "馈"),
    (r"响应", "应"),
    (r"结果", "果"),
    (r"输出", "出"),
    (r"输入", "入"),
    (r"参数", "参"),
    (r"返回值", "返"),
    (r"类型", "类"),
    (r"结构", "构"),
    (r"对象", "物"),
    (r"实例", "例"),
    (r"类", "类"),
    (r"方法", "法"),
    (r"函数", "函"),
    (r"变量", "量"),
    (r"常量", "常"),
    (r"全局", "全"),
    (r"局部", "局"),
    (r"静态", "静"),
    (r"动态", "动"),
    (r"公有", "公"),
    (r"私有", "私"),
    (r"保护", "护"),
    (r"继承", "承"),
    (r"封装", "封"),
    (r"多态", "多"),
    (r"接口", "口"),
    (r"抽象", "抽"),
    (r"实现", "现"),
    (r"重写", "覆"),
    (r"重载", "载"),
    (r"回调", "调"),
    (r"事件", "事"),
    (r"委托", "托"),
    (r"代理", "代"),
    (r"观察者", "观"),
    (r"发布订阅", "发布"),
    (r"消息队列", "队列"),
    (r"任务队列", "任务列"),
    (r"线程池", "线程池"),
    (r"进程池", "进程池"),
    (r"连接池", "连接池"),
    (r"资源池", "资源池"),
    (r"对象池", "对象池"),
    (r"内存池", "内存池"),
    (r"缓冲区", "缓冲"),
    (r"缓存区", "缓存"),
    (r"工作区", "工作区"),
    (r"临时区", "临时区"),
    (r"安全区", "安全区"),
    (r"沙盒", "沙盒"),
    (r"隔离区", "隔离区"),
    (r"白名单", "白名单"),
    (r"黑名单", "黑名单"),
    (r"灰名单", "灰名单"),
    (r"规则", "规"),
    (r"策略", "策"),
    (r"配置", "配"),
    (r"开关", "关"),
    (r"标志位", "标志"),
    (r"状态机", "状态"),
    (r"工作流", "工作流"),
    (r"流水线", "流水线"),
    (r"管道", "管道"),
    (r"过滤器", "过滤"),
    (r"拦截器", "拦截"),
    (r"中间件", "中间"),
    (r"钩子", "钩"),
    (r"回调", "回调"),
    (r"事件总线", "事件总线"),
    (r"命令", "命"),
    (r"查询", "查"),
    (r"事件溯源", "溯源"),
    (r"CQRS", "CQRS"),
    (r" Saga", "Saga"),
    (r"TCC", "TCC"),
    (r"两阶段提交", "两阶段"),
    (r"最终一致性", "最终一致"),
    (r"强一致性", "强一致"),
    (r"弱一致性", "弱一致"),
    (r"顺序一致性", "顺序一致"),
    (r"因果一致性", "因果一致"),
    (r"读写分离", "读写分"),
    (r"主从复制", "主从复"),
    (r"分片", "分片"),
    (r"分区", "分区"),
    (r"分库分表", "分库表"),
    (r"垂直拆分", "垂直拆"),
    (r"水平拆分", "水平拆"),
    (r"冷热分离", "冷热分"),
    (r"动静分离", "动静分"),
    (r"读写分离", "读写分"),
    (r"负载均衡", "负载均"),
    (r"反向代理", "反向代"),
    (r"正向代理", "正向代"),
    (r"网关", "网关"),
    (r"边缘计算", "边缘"),
    (r"CDN", "CDN"),
    (r"DNS", "DNS"),
    (r"HTTP", "HTTP"),
    (r"HTTPS", "HTTPS"),
    (r"TCP", "TCP"),
    (r"UDP", "UDP"),
    (r"WebSocket", "WebSocket"),
    (r"gRPC", "gRPC"),
    (r"REST", "REST"),
    (r"GraphQL", "GraphQL"),
    (r"SOAP", "SOAP"),
    (r"JSON", "JSON"),
    (r"XML", "XML"),
    (r"YAML", "YAML"),
    (r"TOML", "TOML"),
    (r"INI", "INI"),
    (r"CSV", "CSV"),
    (r"TSV", "TSV"),
    (r"Markdown", "Markdown"),
    (r"HTML", "HTML"),
    (r"CSS", "CSS"),
    (r"JavaScript", "JS"),
    (r"TypeScript", "TS"),
    (r"Python", "Python"),
    (r"Java", "Java"),
    (r"Go", "Go"),
    (r"Rust", "Rust"),
    (r"C\\+\\+", "C++"),
    (r"C#", "C#"),
    (r"Ruby", "Ruby"),
    (r"PHP", "PHP"),
    (r"Swift", "Swift"),
    (r"Kotlin", "Kotlin"),
    (r"Scala", "Scala"),
    (r"Lua", "Lua"),
    (r"Perl", "Perl"),
    (r"R", "R"),
    (r"MATLAB", "MATLAB"),
    (r"Shell", "Shell"),
    (r"Bash", "Bash"),
    (r"PowerShell", "PS"),
    (r"SQL", "SQL"),
    (r"NoSQL", "NoSQL"),
    (r"MongoDB", "Mongo"),
    (r"Redis", "Redis"),
    (r"Elasticsearch", "ES"),
    (r"Kafka", "Kafka"),
    (r"RabbitMQ", "Rabbit"),
    (r"NATS", "NATS"),
    (r"Pulsar", "Pulsar"),
    (r"Docker", "Docker"),
    (r"Kubernetes", "K8s"),
    (r" container", "容器"),
    (r" image", "镜像"),
    (r" pod", "Pod"),
    (r" service", "服务"),
    (r" deployment", "部署"),
    (r" configmap", "配置图"),
    (r" secret", "秘钥"),
    (r" ingress", "入口"),
    (r" egress", "出口"),
    (r" namespace", "命名空间"),
    (r" cluster", "集群"),
    (r" node", "节点"),
    (r" master", "主"),
    (r" worker", "工"),
    (r" scheduler", "调度"),
    (r" controller", "控制"),
    (r" etcd", "etcd"),
    (r" API server", "API服"),
    (r" kubelet", "kubelet"),
    (r" kube-proxy", "kube-proxy"),
    (r" CNI", "CNI"),
    (r" CSI", "CSI"),
    (r" CRD", "CRD"),
    (r" operator", "操作器"),
    (r" Helm", "Helm"),
    (r" Kustomize", "Kustomize"),
    (r" Terraform", "Terraform"),
    (r" Ansible", "Ansible"),
    (r" Puppet", "Puppet"),
    (r" Chef", "Chef"),
    (r" SaltStack", "Salt"),
    (r" Jenkins", "Jenkins"),
    (r" GitLab CI", "GitLabCI"),
    (r" GitHub Actions", "GitHubActions"),
    (r" Travis", "Travis"),
    (r" CircleCI", "CircleCI"),
    (r" Drone", "Drone"),
    (r" Argo", "Argo"),
    (r" Spinnaker", "Spinnaker"),
    (r" Flux", "Flux"),
    (r" Tekton", "Tekton"),
    (r" Prow", "Prow"),
    (r" Buildkite", "Buildkite"),
    (r" Zuul", "Zuul"),
    (r" LaunchDarkly", "LaunchDarkly"),
    (r" feature flag", "特性标"),
    (r" A/B test", "AB测"),
    (r" canary", "金丝雀"),
    (r" blue-green", "蓝绿"),
    (r" rolling", "滚动"),
    (r" recreate", "重建"),
    (r" shadow", "影子"),
    (r" mirror", "镜像"),
    (r" traffic split", "流量分"),
    (r" rate limit", "限流"),
    (r" circuit breaker", "熔断"),
    (r" bulkhead", "隔板"),
    (r" timeout", "超时"),
    (r" retry", "重试"),
    (r" fallback", "降级"),
    (r" cache", "缓存"),
    (r" buffer", "缓冲"),
    (r" queue", "队列"),
    (r" pool", "池"),
    (r" throttle", "节流"),
    (r" debounce", "防抖"),
    (r" throttle", "节流"),
    (r" dedup", "去重"),
    (r" batch", "批"),
    (r" stream", "流"),
    (r" pipeline", "管道"),
    (r" fan-out", "扇出"),
    (r" fan-in", "扇入"),
    (r" backpressure", "背压"),
    (r" watermark", "水位"),
    (r" checkpoint", "检查点"),
    (r" snapshot", "快照"),
    (r" WAL", "WAL"),
    (r" redo log", "重做日志"),
    (r" undo log", "撤销日志"),
    (r" binlog", "binlog"),
    (r" slow log", "慢日志"),
    (r" error log", "错误日志"),
    (r" access log", "访问日志"),
    (r" audit log", "审计日志"),
    (r" metric", "指标"),
    (r" trace", "追踪"),
    (r" span", "跨度"),
    (r" baggage", " baggage"),
    (r" tag", "标签"),
    (r" label", "标签"),
    (r" annotation", "注释"),
    (r" event", "事件"),
    (r" log", "日志"),
    (r" metric", "指标"),
    (r" dashboard", "仪表盘"),
    (r" alert", "告警"),
    (r" notification", "通知"),
    (r" incident", "事件"),
    (r" on-call", "值班"),
    (r" runbook", "手册"),
    (r" playbook", "剧本"),
    (r" SOP", "SOP"),
    (r" SLA", "SLA"),
    (r" SLO", "SLO"),
    (r" SLI", "SLI"),
    (r" MTTR", "MTTR"),
    (r" MTBF", "MTBF"),
    (r" MTTF", "MTTF"),
    (r" error budget", "错误预算"),
    (r" burn rate", "燃耗率"),
    (r" toil", "琐事"),
    (r" automation", "自动化"),
    (r" self-healing", "自愈"),
    (r" chaos engineering", "混沌工程"),
    (r" game day", "演练日"),
    (r" postmortem", "事后分析"),
    (r" blameless", "无责"),
    (r" retrospective", "回顾"),
    (r" standup", "站会"),
    (r" sprint", "冲刺"),
    (r" backlog", "待办"),
    (r" epic", "史诗"),
    (r" story", "故事"),
    (r" task", "任务"),
    (r" subtask", "子任务"),
    (r" bug", "缺陷"),
    (r" issue", "问题"),
    (r" ticket", "工单"),
    (r" PR", "PR"),
    (r" MR", "MR"),
    (r" commit", "提交"),
    (r" branch", "分支"),
    (r" tag", "标签"),
    (r" release", "发布"),
    (r" changelog", "变更日志"),
    (r" version", "版本"),
    (r" semver", "语义版本"),
    (r" alpha", "内测"),
    (r" beta", "公测"),
    (r" RC", "候选"),
    (r" GA", "正式"),
    (r" LTS", "长期支持"),
    (r" EOL", "终止"),
    (r" deprecation", "弃用"),
    (r" sunset", "下线"),
    (r" migration", "迁移"),
    (r" upgrade", "升级"),
    (r" downgrade", "降级"),
    (r" patch", "补丁"),
    (r" hotfix", "热修"),
    (r" fix", "修复"),
    (r" feature", "特性"),
    (r" enhancement", "增强"),
    (r" refactor", "重构"),
    (r" perf", "性能"),
    (r" test", "测试"),
    (r" docs", "文档"),
    (r" style", "样式"),
    (r" chore", "杂务"),
    (r" WIP", "进行中"),
    (r" TODO", "待办"),
    (r" FIXME", "待修"),
    (r" HACK", "临时"),
    (r" XXX", "注意"),
    (r" NOTE", "笔记"),
    (r" REVIEW", "审查"),
    (r" OPTIMIZE", "优化"),
    (r" DEPRECATED", "弃用"),
    (r" EXPERIMENTAL", "实验"),
    (r" INTERNAL", "内部"),
    (r" API", "API"),
    (r" SDK", "SDK"),
    (r" CLI", "CLI"),
    (r" UI", "UI"),
    (r" UX", "UX"),
    (r" GUI", "GUI"),
    (r" TUI", "TUI"),
    (r" API", "API"),
    (r" REST", "REST"),
    (r" RPC", "RPC"),
    (r" SOAP", "SOAP"),
    (r" GraphQL", "GraphQL"),
    (r" gRPC", "gRPC"),
    (r" WebSocket", "WebSocket"),
    (r" SSE", "SSE"),
    (r" polling", "轮询"),
    (r" long-polling", "长轮询"),
    (r" push", "推送"),
    (r" pub/sub", "发布订阅"),
    (r" message queue", "消息队列"),
    (r" event bus", "事件总线"),
    (r" CQRS", "CQRS"),
    (r" event sourcing", "事件溯源"),
    (r" saga", "saga"),
    (r" two-phase commit", "两阶段提交"),
    (r" compensation", "补偿"),
    (r" idempotent", "幂等"),
    (r" at-least-once", "至少一次"),
    (r" at-most-once", "至多一次"),
    (r" exactly-once", "恰好一次"),
    (r" delivery guarantee", "投递保证"),
    (r" ordering guarantee", "顺序保证"),
    (r" partition", "分区"),
    (r" replica", "副本"),
    (r" leader", "主"),
    (r" follower", "从"),
    (r" observer", "观察者"),
    (r" learner", "学习者"),
    (r" quorum", "法定人数"),
    (r" consensus", "共识"),
    (r" Paxos", "Paxos"),
    (r" Raft", "Raft"),
    (r" ZAB", "ZAB"),
    (r" Gossip", "Gossip"),
    (r" SWIM", "SWIM"),
    (r" Serf", "Serf"),
    (r" Consul", "Consul"),
    (r" ZooKeeper", "ZK"),
    (r" etcd", "etcd"),
    (r" Dapr", "Dapr"),
    (r" Service Mesh", "服务网格"),
    (r" Istio", "Istio"),
    (r" Linkerd", "Linkerd"),
    (r" Envoy", "Envoy"),
    (r" Nginx", "Nginx"),
    (r" HAProxy", "HAProxy"),
    (r" Traefik", "Traefik"),
    (r" Caddy", "Caddy"),
    (r" Varnish", "Varnish"),
    (r" Squid", "Squid"),
    (r" Memcached", "Memcached"),
    (r" Redis", "Redis"),
    (r" MongoDB", "Mongo"),
    (r" Cassandra", "Cassandra"),
    (r" DynamoDB", "Dynamo"),
    (r" Bigtable", "Bigtable"),
    (r" Spanner", "Spanner"),
    (r" CockroachDB", "Cockroach"),
    (r" TiDB", "TiDB"),
    (r" Vitess", "Vitess"),
    (r" PlanetScale", "PlanetScale"),
    (r" Supabase", "Supabase"),
    (r" Firebase", "Firebase"),
    (r" Appwrite", "Appwrite"),
    (r" PocketBase", "PocketBase"),
    (r" Directus", "Directus"),
    (r" Strapi", "Strapi"),
    (r" Contentful", "Contentful"),
    (r" Sanity", "Sanity"),
    (r" Prismic", "Prismic"),
    (r" ButterCMS", "Butter"),
    (r" Ghost", "Ghost"),
    (r" WordPress", "WP"),
    (r" Drupal", "Drupal"),
    (r" Joomla", "Joomla"),
    (r" Magento", "Magento"),
    (r" Shopify", "Shopify"),
    (r" WooCommerce", "Woo"),
    (r" BigCommerce", "BigC"),
    (r" PrestaShop", "Presta"),
    (r" OpenCart", "OpenCart"),
    (r" osCommerce", "osCommerce"),
    (r" Laravel", "Laravel"),
    (r" Symfony", "Symfony"),
    (r" Django", "Django"),
    (r" Flask", "Flask"),
    (r" FastAPI", "FastAPI"),
    (r" Tornado", "Tornado"),
    (r" aiohttp", "aiohttp"),
    (r" Sanic", "Sanic"),
    (r" Quart", "Quart"),
    (r" Starlette", "Starlette"),
    (r" Express", "Express"),
    (r" Koa", "Koa"),
    (r" NestJS", "Nest"),
    (r" Next.js", "Next"),
    (r" Nuxt", "Nuxt"),
    (r" SvelteKit", "SvelteKit"),
    (r" Remix", "Remix"),
    (r" Astro", "Astro"),
    (r" Gatsby", "Gatsby"),
    (r" Gridsome", "Gridsome"),
    (r" Hexo", "Hexo"),
    (r" Hugo", "Hugo"),
    (r" Jekyll", "Jekyll"),
    (r" Docusaurus", "Docusaurus"),
    (r" VitePress", "VitePress"),
    (r" VuePress", "VuePress"),
    (r" Eleventy", "Eleventy"),
    (r" Middleman", "Middleman"),
    (r" Nanoc", "Nanoc"),
    (r" Pelican", "Pelican"),
    (r" MkDocs", "MkDocs"),
    (r" Docsify", "Docsify"),
    (r" GitBook", "GitBook"),
    (r" ReadTheDocs", "RTD"),
    (r" Confluence", "Confluence"),
    (r" Notion", "Notion"),
    (r" Obsidian", "Obsidian"),
    (r" Roam", "Roam"),
    (r" Logseq", "Logseq"),
    (r" TiddlyWiki", "Tiddly"),
    (r" Wiki.js", "Wiki.js"),
    (r" MediaWiki", "MediaWiki"),
    (r" DokuWiki", "DokuWiki"),
    (r" XWiki", "XWiki"),
    (r" BookStack", "BookStack"),
    (r" Outline", "Outline"),
    (r" Outline", "Outline"),
    (r" Trilium", "Trilium"),
    (r" Joplin", "Joplin"),
    (r" Evernote", "Evernote"),
    (r" OneNote", "OneNote"),
    (r" Bear", "Bear"),
    (r" Ulysses", "Ulysses"),
    (r" Scrivener", "Scrivener"),
    (r" iA Writer", "iA Writer"),
    (r" Typora", "Typora"),
    (r" MarkText", "MarkText"),
    (r" Zettlr", "Zettlr"),
    (r" VS Code", "VS Code"),
    (r" Vim", "Vim"),
    (r" Emacs", "Emacs"),
    (r" Sublime", "Sublime"),
    (r" Atom", "Atom"),
    (r" IntelliJ", "IntelliJ"),
    (r" PyCharm", "PyCharm"),
    (r" WebStorm", "WebStorm"),
    (r" CLion", "CLion"),
    (r" GoLand", "GoLand"),
    (r" RustRover", "RustRover"),
    (r" Rider", "Rider"),
    (r" DataGrip", "DataGrip"),
    (r" PhpStorm", "PhpStorm"),
    (r" RubyMine", "RubyMine"),
    (r" AppCode", "AppCode"),
    (r" Android Studio", "Android Studio"),
    (r" Xcode", "Xcode"),
    (r" Eclipse", "Eclipse"),
    (r" NetBeans", "NetBeans"),
    (r" Visual Studio", "VS"),
    (r" Code::Blocks", "Code::Blocks"),
    (r" Dev-C++", "Dev-C++"),
    (r" Qt Creator", "Qt Creator"),
    (r" GNAT Studio", "GNAT"),
    (r" CLion", "CLion"),
    (r" Cursor", "Cursor"),
    (r" Windsurf", "Windsurf"),
    (r" Trae", "Trae"),
    (r" Zed", "Zed"),
    (r" Fleet", "Fleet"),
    (r" CodeSandbox", "CodeSandbox"),
    (r" StackBlitz", "StackBlitz"),
    (r" Replit", "Replit"),
    (r" Gitpod", "Gitpod"),
    (r" GitHub Codespaces", "Codespaces"),
    (r" GitLab Workspaces", "Workspaces"),
    (r" Bitbucket", "Bitbucket"),
    (r" SourceForge", "SourceForge"),
    (r" Launchpad", "Launchpad"),
    (r" OSDN", "OSDN"),
    (r" Gitee", "Gitee"),
    (r" Coding", "Coding"),
    (r" TaoCode", "TaoCode"),
    (r" Codeup", "Codeup"),
    (r" Gitlink", "Gitlink"),
    (r" Jira", "Jira"),
    (r" Trello", "Trello"),
    (r" Asana", "Asana"),
    (r" Monday", "Monday"),
    (r" ClickUp", "ClickUp"),
    (r" Notion", "Notion"),
    (r" Linear", "Linear"),
    (r" Height", "Height"),
    (r" Shortcut", "Shortcut"),
    (r" Clubhouse", "Clubhouse"),
    (r" Pivotal", "Pivotal"),
    (r" Rally", "Rally"),
    (r" VersionOne", "VersionOne"),
    (r" TargetProcess", "TargetProcess"),
    (r" YouTrack", "YouTrack"),
    (r" Redmine", "Redmine"),
    (r" Trac", "Trac"),
    (r" Mantis", "Mantis"),
    (r" Bugzilla", "Bugzilla"),
    (r" FogBugz", "FogBugz"),
    (r" Zendesk", "Zendesk"),
    (r" Freshdesk", "Freshdesk"),
    (r" ServiceNow", "ServiceNow"),
    (r" Salesforce", "Salesforce"),
    (r" HubSpot", "HubSpot"),
    (r" Zoho", "Zoho"),
    (r" Pipedrive", "Pipedrive"),
    (r" Copper", "Copper"),
    (r" Insightly", "Insightly"),
    (r" Nimble", "Nimble"),
    (r" Close", "Close"),
    (r" Outreach", "Outreach"),
    (r" Salesloft", "Salesloft"),
    (r" Gong", "Gong"),
    (r" Chorus", "Chorus"),
    (r" Clari", "Clari"),
    (r" Revenue.io", "Revenue.io"),
    (r" People.ai", "People.ai"),
    (r" ZoomInfo", "ZoomInfo"),
    (r" Apollo.io", "Apollo.io"),
    (r" Lusha", "Lusha"),
    (r" Cognism", "Cognism"),
    (r" Kaspr", "Kaspr"),
    (r" Seamless.ai", "Seamless"),
    (r" LeadIQ", "LeadIQ"),
    (r" Clearbit", "Clearbit"),
    (r" MadKudu", "MadKudu"),
    (r" 6sense", "6sense"),
    (r" Demandbase", "Demandbase"),
    (r" Terminus", "Terminus"),
    (r" RollWorks", "RollWorks"),
    (r" Triblio", "Triblio"),
    (r" PathFactory", "PathFactory"),
    (r" Uberflip", "Uberflip"),
    (r" Ion Interactive", "Ion"),
    (r" SnapApp", "SnapApp"),
    (r" Ceros", "Ceros"),
    (r" Folloze", "Folloze"),
    (r" Jebbit", "Jebbit"),
    (r" Rock Content", "Rock"),
    (r" Outgrow", "Outgrow"),
    (r" Typeform", "Typeform"),
    (r" SurveyMonkey", "SurveyMonkey"),
    (r" Qualtrics", "Qualtrics"),
    (r" Alchemer", "Alchemer"),
    (r" GetFeedback", "GetFeedback"),
    (r" UserVoice", "UserVoice"),
    (r" Productboard", "Productboard"),
    (r" Aha!", "Aha!"),
    (r" Roadmunk", "Roadmunk"),
    (r" ProductPlan", "ProductPlan"),
    (r" airfocus", "airfocus"),
    (r" Craft", "Craft"),
    (r" Gocious", "Gocious"),
    (r" Harvestr", "Harvestr"),
    (r" Receptive", "Receptive"),
    (r" UserVoice", "UserVoice"),
    (r" Pendo", "Pendo"),
    (r" Appcues", "Appcues"),
    (r" WalkMe", "WalkMe"),
    (r" Whatfix", "Whatfix"),
    (r" Chameleon", "Chameleon"),
    (r" Userlane", "Userlane"),
    (r" Stonly", "Stonly"),
    (r" Spekit", "Spekit"),
    (r" Guru", "Guru"),
    (r" Obie", "Obie"),
    (r" Tettra", "Tettra"),
    (r" Slab", "Slab"),
    (r" Nuclino", "Nuclino"),
    (r" Document360", "Document360"),
    (r" Helpjuice", "Helpjuice"),
    (r" ProProfs", "ProProfs"),
    (r" Freshdesk", "Freshdesk"),
    (r" Zoho Desk", "Zoho Desk"),
    (r" HappyFox", "HappyFox"),
    (r" LiveAgent", "LiveAgent"),
    (r" Kayako", "Kayako"),
    (r" Groove", "Groove"),
    (r" Help Scout", "Help Scout"),
    (r" Front", "Front"),
    (r" Missive", "Missive"),
    (r" Intercom", "Intercom"),
    (r" Crisp", "Crisp"),
    (r" Tidio", "Tidio"),
    (r" Tawk.to", "Tawk"),
    (r" LiveChat", "LiveChat"),
    (r" Olark", "Olark"),
    (r" SnapEngage", "SnapEngage"),
    (r" Pure Chat", "Pure Chat"),
    (r" Chatra", "Chatra"),
    (r" Chaport", "Chaport"),
    (r" Userlike", "Userlike"),
    (r" MobileMonkey", "MobileMonkey"),
    (r" ManyChat", "ManyChat"),
    (r" Chatfuel", "Chatfuel"),
    (r" Botsify", "Botsify"),
    (r" Flow XO", "Flow XO"),
    (r" BotStar", "BotStar"),
    (r" Landbot", "Landbot"),
    (r" Typeform", "Typeform"),
    (r" ConvertKit", "ConvertKit"),
    (r" Mailchimp", "Mailchimp"),
    (r" Sendinblue", "Sendinblue"),
    (r" MailerLite", "MailerLite"),
    (r" Constant Contact", "Constant Contact"),
    (r" AWeber", "AWeber"),
    (r" GetResponse", "GetResponse"),
    (r" Campaign Monitor", "Campaign Monitor"),
    (r" ActiveCampaign", "ActiveCampaign"),
    (r" Drip", "Drip"),
    (r" Klaviyo", "Klaviyo"),
    (r" Omnisend", "Omnisend"),
    (r" Iterable", "Iterable"),
    (r" Braze", "Braze"),
    (r" Customer.io", "Customer.io"),
    (r" Autopilot", "Autopilot"),
    (r" Vero", "Vero"),
    (r" Blueshift", "Blueshift"),
    (r" Cordial", "Cordial"),
    (r" Simon Data", "Simon"),
    (r" Segment", "Segment"),
    (r" mParticle", "mParticle"),
    (r" Tealium", "Tealium"),
    (r" Lytics", "Lytics"),
    (r" Treasure Data", "Treasure Data"),
    (r" Rudderstack", "Rudderstack"),
    (r" Snowplow", "Snowplow"),
    (r" Mixpanel", "Mixpanel"),
    (r" Amplitude", "Amplitude"),
    (r" Heap", "Heap"),
    (r" Kissmetrics", "Kissmetrics"),
    (r" Pendo", "Pendo"),
    (r" FullStory", "FullStory"),
    (r" LogRocket", "LogRocket"),
    (r" Hotjar", "Hotjar"),
    (r" Crazy Egg", "Crazy Egg"),
    (r" Lucky Orange", "Lucky Orange"),
    (r" Mouseflow", "Mouseflow"),
    (r" SessionCam", "SessionCam"),
    (r" Smartlook", "Smartlook"),
    (r" Inspectlet", "Inspectlet"),
    (r" VWO", "VWO"),
    (r" Optimizely", "Optimizely"),
    (r" AB Tasty", "AB Tasty"),
    (r" Google Optimize", "Google Optimize"),
    (r" Adobe Target", "Adobe Target"),
    (r" Monetate", "Monetate"),
    (r" Dynamic Yield", "Dynamic Yield"),
    (r" Evergage", "Evergage"),
    (r" Qubit", "Qubit"),
    (r" Sentient", "Sentient"),
    (r" Intellimize", "Intellimize"),
    (r" Ezoic", "Ezoic"),
    (r" PubWise", "PubWise"),
    (r" AdThrive", "AdThrive"),
    (r" Mediavine", "Mediavine"),
    (r" AdSense", "AdSense"),
    (r" Ad Manager", "Ad Manager"),
    (r" AdMob", "AdMob"),
    (r" Facebook Audience", "FB Audience"),
    (r" Twitter Ads", "Twitter Ads"),
    (r" LinkedIn Ads", "LinkedIn Ads"),
    (r" TikTok Ads", "TikTok Ads"),
    (r" Snapchat Ads", "Snapchat Ads"),
    (r" Pinterest Ads", "Pinterest Ads"),
    (r" Reddit Ads", "Reddit Ads"),
    (r" Quora Ads", "Quora Ads"),
    (r" Taboola", "Taboola"),
    (r" Outbrain", "Outbrain"),
    (r" Revcontent", "Revcontent"),
    (r" MGID", "MGID"),
    (r" Adblade", "Adblade"),
    (r" AdMaven", "AdMaven"),
    (r" PropellerAds", "PropellerAds"),
    (r" PopAds", "PopAds"),
    (r" Adsterra", "Adsterra"),
    (r" HilltopAds", "HilltopAds"),
    (r" ExoClick", "ExoClick"),
    (r" TrafficJunky", "TrafficJunky"),
    (r" TrafficFactory", "TrafficFactory"),
    (r" EroAdvertising", "EroAdvertising"),
    (r" JuicyAds", "JuicyAds"),
    (r" Plugrush", "Plugrush"),
    (r" TwinRed", "TwinRed"),
    (r" AdXXX", "AdXXX"),
    (r" TrafficShop", "TrafficShop"),
    (r" TrafficStars", "TrafficStars"),
    (r" DaoPush", "DaoPush"),
    (r" NotifAd", "NotifAd"),
    (r" EvaDav", "EvaDav"),
    (r" MegaPush", "MegaPush"),
    (r" RichPush", "RichPush"),
    (r" AdMessenger", "AdMessenger"),
    (r" Push.House", "Push.House"),
    (r" PushGround", "PushGround"),
    (r" ZeroPark", "ZeroPark"),
    (r" TONIC.", "TONIC"),
    (r" DatsPush", "DatsPush"),
    (r" RollerAds", "RollerAds"),
    (r" AdOperator", "AdOperator"),
    (r" MyBid", "MyBid"),
    (r" ActiveRevenue", "ActiveRevenue"),
    (r" Adperium", "Adperium"),
    (r" AdSupply", "AdSupply"),
    (r" BidVertiser", "BidVertiser"),
    (r" ClickAdu", "ClickAdu"),
    (r" AdCash", "AdCash"),
    (r" AdKernel", "AdKernel"),
    (r" AdMaven", "AdMaven"),
    (r" AdMedia", "AdMedia"),
    (r" Adnium", "Adnium"),
    (r" AdOnion", "AdOnion"),
    (r" AdPlexity", "AdPlexity"),
    (r" AdRecover", "AdRecover"),
    (r" AdRefresh", "AdRefresh"),
    (r" AdRelevantis", "AdRelevantis"),
    (r" AdRiver", "AdRiver"),
    (r" AdRoll", "AdRoll"),
    (r" AdRubiCon", "AdRubiCon"),
    (r" AdScale", "AdScale"),
    (r" AdServer", "AdServer"),
    (r" AdSheriff", "AdSheriff"),
    (r" AdShuffle", "AdShuffle"),
    (r" AdSorcery", "AdSorcery"),
    (r" AdSpirit", "AdSpirit"),
    (r" AdSpruce", "AdSpruce"),
    (r" AdStx", "AdStx"),
    (r" AdSupply", "AdSupply"),
    (r" AdSwipe", "AdSwipe"),
    (r" AdTaily", "AdTaily"),
    (r" AdTech", "AdTech"),
    (r" AdTelligent", "AdTelligent"),
    (r" AdThrive", "AdThrive"),
    (r" AdTiger", "AdTiger"),
    (r" AdToll", "AdToll"),
    (r" AdTotal", "AdTotal"),
    (r" AdTraff", "AdTraff"),
    (r" AdTrust", "AdTrust"),
    (r" AdUnity", "AdUnity"),
    (r" AdUp", "AdUp"),
    (r" AdUser", "AdUser"),
    (r" AdValue", "AdValue"),
    (r" AdVault", "AdVault"),
    (r" AdVestor", "AdVestor"),
    (r" AdView", "AdView"),
    (r" AdVlion", "AdVlion"),
    (r" AdWallet", "AdWallet"),
    (r" AdWap", "AdWap"),
    (r" AdWeb", "AdWeb"),
    (r" AdWing", "AdWing"),
    (r" AdWiz", "AdWiz"),
    (r" AdWorld", "AdWorld"),
    (r" AdX", "AdX"),
    (r" AdYogi", "AdYogi"),
    (r" AdYouniverse", "AdYouniverse"),
    (r" AdZerk", "AdZerk"),
    (r" AdZeta", "AdZeta"),
    (r" AdZoom", "AdZoom"),
    (r" AdZouk", "AdZouk"),
    (r" AdZuna", "AdZuna"),
    (r" Ad4Game", "Ad4Game"),
    (r" Ad6Media", "Ad6Media"),
    (r" Ad8", "Ad8"),
    (r" Ad91", "Ad91"),
    (r" AdABC", "AdABC"),
    (r" AdAsia", "AdAsia"),
    (r" AdBack", "AdBack"),
    (r" AdBand", "AdBand"),
    (r" AdBar", "AdBar"),
    (r" AdBase", "AdBase"),
    (r" AdBazaar", "AdBazaar"),
    (r" AdBeat", "AdBeat"),
    (r" AdBrite", "AdBrite"),
    (r" AdButler", "AdButler"),
    (r" AdCake", "AdCake"),
    (r" AdCamp", "AdCamp"),
    (r" AdCash", "AdCash"),
    (r" AdCast", "AdCast"),
    (r" AdCel", "AdCel"),
    (r" AdCentric", "AdCentric"),
    (r" AdCirrus", "AdCirrus"),
    (r" AdClick", "AdClick"),
    (r" AdCloud", "AdCloud"),
    (r" AdColony", "AdColony"),
    (r" AdCurious", "AdCurious"),
    (r" AdDecisive", "AdDecisive"),
    (r" AdDynamo", "AdDynamo"),
    (r" AdElement", "AdElement"),
    (r" AdEngage", "AdEngage"),
    (r" AdFalcon", "AdFalcon"),
    (r" AdFill", "AdFill"),
    (r" AdFonic", "AdFonic"),
    (r" AdFox", "AdFox"),
    (r" AdFractal", "AdFractal"),
    (r" AdFrontier", "AdFrontier"),
    (r" AdGent", "AdGent"),
    (r" AdGibbon", "AdGibbon"),
    (r" AdGilo", "AdGilo"),
    (r" AdGreet", "AdGreet"),
    (r" AdGuitar", "AdGuitar"),
    (r" AdGuna", "AdGuna"),
    (r" AdHall", "AdHall"),
    (r" AdHaven", "AdHaven"),
    (r" AdHitz", "AdHitz"),
    (r" AdHoc", "AdHoc"),
    (r" AdHold", "AdHold"),
    (r" AdHornet", "AdHornet"),
    (r" AdHost", "AdHost"),
    (r" AdHybrid", "AdHybrid"),
    (r" AdIcarus", "AdIcarus"),
    (r" AdIgnite", "AdIgnite"),
    (r" AdImpact", "AdImpact"),
    (r" AdInca", "AdInca"),
    (r" AdInsight", "AdInsight"),
    (r" AdInvent", "AdInvent"),
    (r" AdIq", "AdIq"),
    (r" AdJitsu", "AdJitsu"),
    (r" AdJuggler", "AdJuggler"),
    (r" AdJumbo", "AdJumbo"),
    (r" AdJuster", "AdJuster"),
    (r" AdKarma", "AdKarma"),
    (r" AdKlick", "AdKlick"),
    (r" AdKode", "AdKode"),
    (r" AdLantic", "AdLantic"),
    (r" AdLeap", "AdLeap"),
    (r" AdLib", "AdLib"),
    (r" AdLion", "AdLion"),
    (r" AdLoaded", "AdLoaded"),
    (r" AdLogic", "AdLogic"),
    (r" AdLoud", "AdLoud"),
    (r" AdLux", "AdLux"),
    (r" AdMagic", "AdMagic"),
    (r" AdMail", "AdMail"),
    (r" AdMaker", "AdMaker"),
    (r" AdMan", "AdMan"),
    (r" AdMaven", "AdMaven"),
    (r" AdMax", "AdMax"),
    (r" AdMedia", "AdMedia"),
    (r" AdMediastic", "AdMediastic"),
    (r" AdMeta", "AdMeta"),
    (r" AdMobi", "AdMobi"),
    (r" AdMobius", "AdMobius"),
    (r" AdModern", "AdModern"),
    (r" AdMomentum", "AdMomentum"),
    (r" AdMotion", "AdMotion"),
    (r" AdNectar", "AdNectar"),
    (r" AdNemo", "AdNemo"),
    (r" AdNexus", "AdNexus"),
    (r" AdNext", "AdNext"),
    (r" AdNgin", "AdNgin"),
    (r" AdNubo", "AdNubo"),
    (r" AdOcean", "AdOcean"),
    (r" AdOcean", "AdOcean"),
    (r" AdOn", "AdOn"),
    (r" AdOnion", "AdOnion"),
    (r" AdOptima", "AdOptima"),
    (r" AdOrbit", "AdOrbit"),
    (r" AdOrso", "AdOrso"),
    (r" AdOsmosis", "AdOsmosis"),
    (r" AdPace", "AdPace"),
    (r" AdParlor", "AdParlor"),
    (r" AdPass", "AdPass"),
    (r" AdPatron", "AdPatron"),
    (r" AdPay", "AdPay"),
    (r" AdPeak", "AdPeak"),
    (r" AdPerfect", "AdPerfect"),
    (r" AdPeriscope", "AdPeriscope"),
    (r" AdPerson", "AdPerson"),
    (r" AdPilot", "AdPilot"),
    (r" AdPlan", "AdPlan"),
    (r" AdPlanet", "AdPlanet"),
    (r" AdPlus", "AdPlus"),
    (r" AdPoll", "AdPoll"),
    (r" AdPop", "AdPop"),
    (r" AdPortal", "AdPortal"),
    (r" AdPost", "AdPost"),
    (r" AdPrelude", "AdPrelude"),
    (r" AdPrime", "AdPrime"),
    (r" AdPrior", "AdPrior"),
    (r" AdProfit", "AdProfit"),
    (r" AdProton", "AdProton"),
    (r" AdPubs", "AdPubs"),
    (r" AdPulse", "AdPulse"),
    (r" AdQuantum", "AdQuantum"),
    (r" AdQuick", "AdQuick"),
    (r" AdRally", "AdRally"),
    (r" AdRamp", "AdRamp"),
    (r" AdRapt", "AdRapt"),
    (r" AdReady", "AdReady"),
    (r" AdRealm", "AdRealm"),
    (r" AdRec", "AdRec"),
    (r" AdReel", "AdReel"),
    (r" AdRelevant", "AdRelevant"),
    (r" AdRemix", "AdRemix"),
    (r" AdReps", "AdReps"),
    (r" AdRev", "AdRev"),
    (r" AdRiver", "AdRiver"),
    (r" AdRoar", "AdRoar"),
    (r" AdRocket", "AdRocket"),
    (r" AdRoll", "AdRoll"),
    (r" AdRubi", "AdRubi"),
    (r" AdRun", "AdRun"),
    (r" AdRush", "AdRush"),
    (r" AdSage", "AdSage"),
    (r" AdSail", "AdSail"),
    (r" AdSats", "AdSats"),
    (r" AdScale", "AdScale"),
    (r" AdScoop", "AdScoop"),
    (r" AdScout", "AdScout"),
    (r" AdSense", "AdSense"),
    (r" AdSerious", "AdSerious"),
    (r" AdServe", "AdServe"),
    (r" AdSession", "AdSession"),
    (r" AdSet", "AdSet"),
    (r" AdShade", "AdShade"),
    (r" AdShare", "AdShare"),
    (r" AdShark", "AdShark"),
    (r" AdSheriff", "AdSheriff"),
    (r" AdShift", "AdShift"),
    (r" AdShip", "AdShip"),
    (r" AdShoot", "AdShoot"),
    (r" AdShop", "AdShop"),
    (r" AdShot", "AdShot"),
    (r" AdShuffle", "AdShuffle"),
    (r" AdSide", "AdSide"),
    (r" AdSign", "AdSign"),
    (r" AdSimple", "AdSimple"),
    (r" AdSine", "AdSine"),
    (r" AdSingular", "AdSingular"),
    (r" AdSite", "AdSite"),
    (r" AdSki", "AdSki"),
    (r" AdSky", "AdSky"),
    (r" AdSlide", "AdSlide"),
    (r" AdSlot", "AdSlot"),
    (r" AdSmack", "AdSmack"),
    (r" AdSmart", "AdSmart"),
    (r" AdSmit", "AdSmit"),
    (r" AdSnap", "AdSnap"),
    (r" AdSniper", "AdSniper"),
    (r" AdSocial", "AdSocial"),
    (r" AdSo", "AdSo"),
    (r" AdSoft", "AdSoft"),
    (r" AdSolve", "AdSolve"),
    (r" AdSonar", "AdSonar"),
    (r" AdSonic", "AdSonic"),
    (r" AdSort", "AdSort"),
    (r" AdSpace", "AdSpace"),
    (r" AdSpark", "AdSpark"),
    (r" AdSpire", "AdSpire"),
    (r" AdSport", "AdSport"),
    (r" AdSpot", "AdSpot"),
    (r" AdSprint", "AdSprint"),
    (r" AdSpy", "AdSpy"),
    (r" AdSquare", "AdSquare"),
    (r" AdStack", "AdStack"),
    (r" AdStage", "AdStage"),
    (r" AdStamp", "AdStamp"),
    (r" AdStand", "AdStand"),
    (r" AdStar", "AdStar"),
    (r" AdStat", "AdStat"),
    (r" AdStell", "AdStell"),
    (r" AdStep", "AdStep"),
    (r" AdStitch", "AdStitch"),
    (r" AdStorm", "AdStorm"),
    (r" AdStream", "AdStream"),
    (r" AdStride", "AdStride"),
    (r" AdStrike", "AdStrike"),
    (r" AdStrip", "AdStrip"),
    (r" AdStudio", "AdStudio"),
    (r" AdStx", "AdStx"),
    (r" AdSuite", "AdSuite"),
    (r" AdSum", "AdSum"),
    (r" AdSun", "AdSun"),
    (r" AdSupply", "AdSupply"),
    (r" AdSurf", "AdSurf"),
    (r" AdSwipe", "AdSwipe"),
    (r" AdSwitch", "AdSwitch"),
    (r" AdSync", "AdSync"),
    (r" AdTab", "AdTab"),
    (r" AdTact", "AdTact"),
    (r" AdTail", "AdTail"),
    (r" AdTaily", "AdTaily"),
    (r" AdTake", "AdTake"),
    (r" AdTale", "AdTale"),
    (r" AdTall", "AdTall"),
    (r" AdTally", "AdTally"),
    (r" AdTamer", "AdTamer"),
    (r" AdTap", "AdTap"),
    (r" AdTarget", "AdTarget"),
    (r" AdTaxi", "AdTaxi"),
    (r" AdTeam", "AdTeam"),
    (r" AdTech", "AdTech"),
    (r" AdTelligent", "AdTelligent"),
    (r" AdTempo", "AdTempo"),
    (r" AdTerra", "AdTerra"),
    (r" AdTest", "AdTest"),
    (r" AdText", "AdText"),
    (r" AdThrive", "AdThrive"),
    (r" AdTiger", "AdTiger"),
    (r" AdTilt", "AdTilt"),
    (r" AdTimber", "AdTimber"),
    (r" AdTime", "AdTime"),
    (r" AdToll", "AdToll"),
    (r" AdTomo", "AdTomo"),
    (r" AdTone", "AdTone"),
    (r" AdTop", "AdTop"),
    (r" AdTotal", "AdTotal"),
    (r" AdTower", "AdTower"),
    (r" AdTown", "AdTown"),
    (r" AdTrack", "AdTrack"),
    (r" AdTrade", "AdTrade"),
    (r" AdTrail", "AdTrail"),
    (r" AdTrain", "AdTrain"),
    (r" AdTrak", "AdTrak"),
    (r" AdTrans", "AdTrans"),
    (r" AdTrap", "AdTrap"),
    (r" AdTravel", "AdTravel"),
    (r" AdTree", "AdTree"),
    (r" AdTrend", "AdTrend"),
    (r" AdTribe", "AdTribe"),
    (r" AdTrick", "AdTrick"),
    (r" AdTrip", "AdTrip"),
    (r" AdTrivia", "AdTrivia"),
    (r" AdTroll", "AdTroll"),
    (r" AdTron", "AdTron"),
    (r" AdTroop", "AdTroop"),
    (r" AdTropical", "AdTropical"),
    (r" AdTruck", "AdTruck"),
    (r" AdTrue", "AdTrue"),
    (r" AdTrump", "AdTrump"),
    (r" AdTrust", "AdTrust"),
    (r" AdTube", "AdTube"),
    (r" AdTuna", "AdTuna"),
    (r" AdTurbo", "AdTurbo"),
    (r" AdTurn", "AdTurn"),
    (r" AdTutor", "AdTutor"),
    (r" AdTwist", "AdTwist"),
    (r" AdType", "AdType"),
    (r" AdUber", "AdUber"),
    (r" AdUltimate", "AdUltimate"),
    (r" AdUltra", "AdUltra"),
    (r" AdUmble", "AdUmble"),
    (r" AdUnity", "AdUnity"),
    (r" AdUp", "AdUp"),
    (r" AdUptake", "AdUptake"),
    (r" AdUrban", "AdUrban"),
    (r" AdUrgent", "AdUrgent"),
    (r" AdUser", "AdUser"),
    (r" AdUtility", "AdUtility"),
    (r" AdValue", "AdValue"),
    (r" AdVault", "AdVault"),
    (r" AdVector", "AdVector"),
    (r" AdVega", "AdVega"),
    (r" AdVelvet", "AdVelvet"),
    (r" AdVendor", "AdVendor"),
    (r" AdVenture", "AdVenture"),
    (r" AdVerdict", "AdVerdict"),
    (r" AdVerge", "AdVerge"),
    (r" AdVerify", "AdVerify"),
    (r" AdVersatile", "AdVersatile"),
    (r" AdVersion", "AdVersion"),
    (r" AdVertex", "AdVertex"),
    (r" AdVertical", "AdVertical"),
    (r" AdVest", "AdVest"),
    (r" AdVestor", "AdVestor"),
    (r" AdVibe", "AdVibe"),
    (r" AdVictor", "AdVictor"),
    (r" AdVideo", "AdVideo"),
    (r" AdView", "AdView"),
    (r" AdViking", "AdViking"),
    (r" AdVillage", "AdVillage"),
    (r" AdVine", "AdVine"),
    (r" AdViral", "AdViral"),
    (r" AdVirtue", "AdVirtue"),
    (r" AdVision", "AdVision"),
    (r" AdVisit", "AdVisit"),
    (r" AdVista", "AdVista"),
    (r" AdVisual", "AdVisual"),
    (r" AdVital", "AdVital"),
    (r" AdViva", "AdViva"),
    (r" AdVivid", "AdVivid"),
    (r" AdVlion", "AdVlion"),
    (r" AdVoice", "AdVoice"),
    (r" AdVoid", "AdVoid"),
    (r" AdVolume", "AdVolume"),
    (r" AdVolt", "AdVolt"),
    (r" AdVote", "AdVote"),
    (r" AdVoyage", "AdVoyage"),
    (r" AdVulture", "AdVulture"),
    (r" AdWallet", "AdWallet"),
    (r" AdWap", "AdWap"),
    (r" AdWar", "AdWar"),
    (r" AdWarp", "AdWarp"),
    (r" AdWave", "AdWave"),
    (r" AdWay", "AdWay"),
    (r" AdWeb", "AdWeb"),
    (r" AdWealth", "AdWealth"),
    (r" AdWeek", "AdWeek"),
    (r" AdWing", "AdWing"),
    (r" AdWin", "AdWin"),
    (r" AdWink", "AdWink"),
    (r" AdWire", "AdWire"),
    (r" AdWisdom", "AdWisdom"),
    (r" AdWise", "AdWise"),
    (r" AdWish", "AdWish"),
    (r" AdWit", "AdWit"),
    (r" AdWizard", "AdWizard"),
    (r" AdWolf", "AdWolf"),
    (r" AdWonder", "AdWonder"),
    (r" AdWood", "AdWood"),
    (r" AdWord", "AdWord"),
    (r" AdWork", "AdWork"),
    (r" AdWorld", "AdWorld"),
    (r" AdWorth", "AdWorth"),
    (r" AdWrite", "AdWrite"),
    (r" AdX", "AdX"),
    (r" AdYell", "AdYell"),
    (r" AdYoga", "AdYoga"),
    (r" AdYonder", "AdYonder"),
    (r" AdYou", "AdYou"),
    (r" AdYoung", "AdYoung"),
    (r" AdYours", "AdYours"),
    (r" AdZen", "AdZen"),
    (r" AdZero", "AdZero"),
    (r" AdZest", "AdZest"),
    (r" AdZilla", "AdZilla"),
    (r" AdZing", "AdZing"),
    (r" AdZone", "AdZone"),
    (r" AdZoom", "AdZoom"),
    (r" AdZouk", "AdZouk"),
    (r" AdZuna", "AdZuna"),
    (r" AdZing", "AdZing"),
]

# ── 安全词保护列表（不可转换的部分） ──
SAFE_PATTERNS = [
    r'```[\s\S]*?```',           # 代码块
    r'`[^`]+`',                    # 行内代码
    r'https?://\S+',              # URL
    r'\{\{.*?\}\}',               # 模板变量
    r'\$\{.*?\}',                  # shell变量
    r'"""[\s\S]*?"""',            # Python docstring
    r"'''[\s\S]*?'''",            # Python docstring
    r'"[^"]*"',                    # 双引号字符串
    r"'[^']*'",                    # 单引号字符串
    r'\b[A-Za-z_][A-Za-z0-9_]*\b', # 英文标识符
]

class ClassicalChineseCompressor:
    """
    文言文 Token 压缩器
    
    将中文提示/注释/内部思考转换为凝练文言文表达，
    降低 Token 消耗，但保证：
    1. 代码逻辑不变
    2. API调用不变
    3. 最终用户输出仍为现代汉语
    4. 语义100%等价
    """

    def __init__(self, enabled: bool = True) -> None:
        self.enabled = enabled
        self._stats = {"converted": 0, "original_tokens_est": 0, "saved_tokens_est": 0}

    def can_compress(self, text: str) -> bool:
        """判断文本是否适合文言文压缩"""
        if not self.enabled:
            return False
        # 必须是中文为主
        chinese_chars = len(re.findall(r'[\u4e00-\u9fff]', text))
        total_chars = len(text)
        if chinese_chars < total_chars * 0.3:
            return False
        # 不能是最终用户输出（用户-facing 内容不转换）
        if "【最终输出给用户】" in text or "USER_FACING" in text:
            return False
        return True

    def compress(self, text: str) -> str:
        """执行压缩转换"""
        if not self.can_compress(text):
            return text
        
        # 1. 保护安全区域
        protected: list[str] = []
        def _protect(match: re.Match) -> str:
            protected.append(match.group(0))
            return f"__PROT_{len(protected)-1}__"
        
        safe_text = text
        for pattern in SAFE_PATTERNS:
            safe_text = re.sub(pattern, _protect, safe_text)
        
        # 2. 应用转换规则
        converted = safe_text
        original_len = len(converted)
        for pattern, replacement in CLASSICAL_PATTERNS:
            converted = re.sub(pattern, replacement, converted)
        
        # 3. 恢复保护区域
        for i, val in enumerate(protected):
            converted = converted.replace(f"__PROT_{i}__", val)
        
        # 4. 统计
        saved = original_len - len(converted)
        self._stats["converted"] += 1
        self._stats["original_tokens_est"] += original_len
        self._stats["saved_tokens_est"] += max(saved, 0)
        
        return converted

    def compress_system_prompt(self, prompt: str) -> str:
        """压缩系统提示（内部使用）"""
        # 系统提示通常很长，适合压缩
        return self.compress(prompt)

    def compress_thought(self, thought: str) -> str:
        """压缩思考过程（Chain-of-Thought）"""
        return self.compress(thought)

    def compress_comment(self, comment: str) -> str:
        """压缩代码注释"""
        return self.compress(comment)

    def get_stats(self) -> dict:
        return self._stats.copy()

# 全局实例
_cc = ClassicalChineseCompressor()

def compress_for_token_saving(text: str) -> str:
    """便捷函数：将中文文本转换为文言文以节省 Token"""
    return _cc.compress(text)

# 使用示例（注释中展示）
USAGE_EXAMPLE = """
# 使用前：
# "首先，我们需要检查文件是否存在，然后读取内容，最后返回结果。"
# Token 估算：约 30 tokens

# 使用后：
# "先须察文件之有无，继而读其内容，终返其果。"
# Token 估算：约 15 tokens（节省 50%）
"""
